### PR TITLE
Milestone_1_header/footer

### PR DESCRIPTION
**Pull request by SamanAtashi**
# Header / Footer clone part of the website [Newsweek](https://web.archive.org/web/20210120125445/https://www.newsweek.com/).

- Bootstrap used as the main tool to style items
- media query is used in the minority of cases
- and HTML 5

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @SamanAtashi  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone almost looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the requirements very carefully, keep it up, and your project is really almost done.
:+1: The usage of CSS variables is very commendable
:+1: Almost all of the requirements have been implemented right :heavy_check_mark: 
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] The navbar is a bit distorted on screens between 320px - 370px which is not the case on original screens

| Your clone | Original page |
| --- | --- |
| Screenshot from 2021-04-12 15-41-34| Screenshot from 2021-04-12 15-42-29 |

:point_right: Could you see the difference :question: :question: :question: 
Well, the user icon is overlapping other content on the left part
___

_:warning: Reminder: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#), when you reach to the limit of 3 code reviews and your project was not approved, you will need to repeat the project. => You are now left with 2 chance to get a review on this project. So implement the requested changes very carefully. If you think that the code review was not fair, you can request a second-opinion using [this form](https://airtable.com/shrmBIv6cXYrq4Fgv)._

_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @SamanAtashi  :handshake: :handshake: :handshake: 
:+1: It's very nice that you have tried to implement the requested change

#### :warning: However the requested change is not yet implemented successfully, don't feel discouraged because of being asked some changes more and more, that's because this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] While trying to implement that requested change, there is a new issue which is introduced on your clone, kindly make sure sure that you compare your clone with the origin web page that you are cloning on mentioned screen sizes

| Your clone | Original page |
| --- | --- |
| Screenshot from 2021-04-12 16-49-06| Screenshot from 2021-04-12 15-42-29 |
 => The navbar is now more distorted on screen width 320 px - 380px
___


_:warning: Reminder: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#), when you reach to the limit of 3 code reviews and your project was not approved, you will need to repeat the project. => You are now left with only one (1) chance to get a review on this project. So implement the requested changes very carefully. If you think that the code review was not fair, you can request a second-opinion using [this form](https://airtable.com/shrmBIv6cXYrq4Fgv)._

_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by SamanAtashi** [comment]
> # Status: Changes Required 🚦 ⚠️
> ## Hello @SamanAtashi 🤝 🤝 🤝
> 👍 It's very nice that you have tried to implement the requested change
> 
> #### ⚠️ However the requested change is not yet implemented successfully, don't feel discouraged because of being asked some changes more and more, that's because this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below 👇 👇 👇
> ### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding
> # [Required Changes] 🔴
> * [ ]  While trying to implement that requested change, there is a new issue which is introduced on your clone, kindly make sure sure that you compare your clone with the origin web page that you are cloning on mentioned screen sizes
> 
> Your clone	Original page
> Screenshot from 2021-04-12 16-49-06	Screenshot from 2021-04-12 15-42-29
> => The navbar is now more distorted on screen width 320 px - 380px	
> _⚠️ Reminder: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#), when you reach to the limit of 3 code reviews and your project was not approved, you will need to repeat the project. => You are now left with only one (1) chance to get a review on this project. So implement the requested changes very carefully. If you think that the code review was not fair, you can request a second-opinion using [this form](https://airtable.com/shrmBIv6cXYrq4Fgv)._
> 
> _If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._
> 
> [GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)
> 
> _Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_


Should i make it so that the right items overlap on the logo (like the original website) ????

**Comment by SamanAtashi** [comment]
> # Status: Changes Required 🚦 ⚠️
> ## Hello @SamanAtashi 🤝 🤝 🤝
> 👍 It's very nice that you have tried to implement the requested change
> 
> #### ⚠️ However the requested change is not yet implemented successfully, don't feel discouraged because of being asked some changes more and more, that's because this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below 👇 👇 👇
> ### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding
> # [Required Changes] 🔴
> * [ ]  While trying to implement that requested change, there is a new issue which is introduced on your clone, kindly make sure sure that you compare your clone with the origin web page that you are cloning on mentioned screen sizes
> 
> Your clone	Original page
> Screenshot from 2021-04-12 16-49-06	Screenshot from 2021-04-12 15-42-29
> => The navbar is now more distorted on screen width 320 px - 380px	
> _⚠️ Reminder: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#), when you reach to the limit of 3 code reviews and your project was not approved, you will need to repeat the project. => You are now left with only one (1) chance to get a review on this project. So implement the requested changes very carefully. If you think that the code review was not fair, you can request a second-opinion using [this form](https://airtable.com/shrmBIv6cXYrq4Fgv)._
> 
> _If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._
> 
> [GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)
> 
> _Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by SamanAtashi** [comment]
@descholar-ceo 

Hello, I managed to resize the button, now in 320px, we have similar look as in original website.
Is it good? or should I change it?

**Comment by chubaquelo** [comment]
# STATUS: Approved 🎉🔋👏



Yeah! that was it! Now your layout looks great on mobile phones with small screens like mine.
You can continue with your next milestones!

**Congratulations and good luck with next milestones!**

---

### If you have any question kindly reach me on slack as 'Sergio Obolevich'
Github: [@**chubaquelo**](https://www.github.com/chubaquelo)

### **HAPPY CODING 💻🚀🎉**

**Review by sergioobolevich — APPROVED** [review]
# STATUS: Approved 🎉🔋👏



Yeah! that was it! Now your layout looks great on mobile phones with small screens like mine.
You can continue with your next milestones!

**Congratulations and good luck with next milestones!**

---

### If you have any question kindly reach me on slack as 'Sergio Obolevich'
Github: [@**chubaquelo**](https://www.github.com/chubaquelo)

### **HAPPY CODING 💻🚀🎉**

**Pull request merged**
